# Generated by Django 4.1.2 on 2022-11-24 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stack_api', '0002_rename_question_comment_ask_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='ask_question',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='askquestionmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL),
        ),
    ]
