# Generated by Django 4.1.2 on 2022-11-24 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stack_api', '0003_rename_ask_question_comment_post_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_reply', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_comment', to=settings.AUTH_USER_MODEL)),
                ('user_coment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stack_api.comment')),
            ],
        ),
    ]
